name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Download
      run: |
        C:
        mkdir work
        cd work
        Invoke-WebRequest https://raw.githubusercontent.com/JosephM101/uupdump_cli/main/uupdump_cli.py -OutFile uupdump_cli.py
        pip3 install py7zr requests
        python3 uupdump_cli.py Dev arm64 PROFESSIONAL
        dir
        cd 22*
        .\uup_download_windows.cmd
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: uupfiles
        path: C:\work
